//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBartender.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.DropHistory = new HashSet<DropHistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> idAuthorization { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DropHistory> DropHistory { get; set; }
    }
}
