//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBartender.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropHistory
    {
        public int id { get; set; }
        public Nullable<int> idParameters { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> DateDrop { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Parameters Parameters { get; set; }
    }
}
